baseURL = "https://wiki.tbbs.me"
title = "Toolbox Wiki"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "Toolbox Bodensee e.V."

theme = "minimo"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "de"

[params.info]
description = "Minimalist theme for Hugo"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "MunifTanjim"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.twitter]
page = "toolboxbodensee" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "kontakt@toolbox-bodensee.de"
github = "toolboxbodensee"
twitter = "toolboxbodensee"
youtube = "UCoTB8frSN0OT2mZl2IXSsDA"

[params.comments]
enable = false

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/toolboxbodensee/toolbox-wiki"

[languages]

[languages.de]
lang = "de"
languageName = "Deutsch"
weight = 1

[languages.en]
lang = "en"
languageName = "English"
weight = 1
